from django.urls import path
from please_website_app import views


urlpatterns = [
    path('', views.index),
    path('home', views.index, name='home'),
    path('index', views.index, name='index'),
    path('presse', views.presse, name='presse'),
    path('team', views.team, name='team'),
    path('jobs', views.jobs, name='jobs'),
    path('city_manager', views.city_manager, name='city_manager'),
    path('city_manager_franchise', views.city_manager_franchise, name='city_manager_franchise'),
    path('city_manager_creation_business', views.city_manager_creation_business, name='city_manager_creation_business'),
    path('city_manager_idee_business', views.city_manager_idee_business, name='city_manager_idee_business'),
    path('city_manager_recherche_emploi', views.city_manager_recherche_emploi, name='city_manager_recherche_emploi'),
    path('collectivites', views.collectivites, name='collectivites'),
    path('contact', views.contact, name='contact'),
    path('contact_cm', views.contact_cm, name='contact_cm'),
    path('contact_collectivite', views.contact_city, name='contact_city'),
    path('contact_commercant', views.contact_merchant, name='contact_merchant'),
    path('contact_livreur', views.contact_delivery, name='contact_delivery'),
    path('ville/<name>', views.city, name='city-detail'),
    path('commercants', views.commercants, name='commercants'),
    path('temoignages', views.testimonials, name='temoignages'),
    path('livreurs', views.livreurs, name='livreurs'),
    path('candidature', views.candidature, name='candidature'),
    path('devenir_cm', views.devenir_cm, name='devenir_cm'),
    path('login', views.login_cm, name='login'),
    path('app', views.app, name='app'),
    path('app_2', views.app_2, name='app_2'),
    path('app_3', views.app_3, name='app_3'),
    path('app_commerce', views.app_commerce, name='app_commerce'),
    path('app_livreur', views.app_livreur, name='app_livreur'),
    path('merci', views.merci, name='merci'),
    path('merci_inscription', views.merci_signup, name='merci_inscription'),
    path('logout', views.logout_app, name='logout'),
    path('task_completed', views.task_completed, name='task_completed'),
    path('nps', views.nps, name='nps'),
]
