# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-07 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_website_app', '0002_auto_20180307_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(blank=True, max_length=500, null=True)),
                ('testimonial', models.TextField(blank=True, max_length=5000, null=True)),
                ('city_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
