# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-08 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_website_app', '0009_auto_20180308_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='abstract',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
    ]
