# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-08 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_website_app', '0010_job_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
