# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-08 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_website_app', '0012_auto_20180308_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='top',
            field=models.NullBooleanField(),
        ),
    ]
