# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-12 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_website_app', '0013_article_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
