# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-17 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_website_app', '0014_city_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='press_release',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='video_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
