# Generated by Django 2.0.3 on 2018-03-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_website_app', '0017_auto_20180318_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='logo_white',
            field=models.ImageField(blank=True, null=True, upload_to='please_website_app/static/img/admin'),
        ),
    ]
