# Generated by Django 2.0.3 on 2018-03-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_website_app', '0018_auto_20180327_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/site/')),
            ],
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='partner_name',
            new_name='partner_last_name',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='abstract',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='partner_first_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='logo_color',
            field=models.ImageField(blank=True, null=True, upload_to='documents/article/color_logos'),
        ),
        migrations.AlterField(
            model_name='article',
            name='logo_grey',
            field=models.ImageField(blank=True, null=True, upload_to='documents/article/grey_logos'),
        ),
        migrations.AlterField(
            model_name='article',
            name='logo_white',
            field=models.ImageField(blank=True, null=True, upload_to='documents/article/white_logos'),
        ),
        migrations.AlterField(
            model_name='city',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='documents/city/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='documents/team/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='documents/testimonials/'),
        ),
    ]
