# Generated by Django 2.0.3 on 2018-03-28 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_website_app', '0019_auto_20180328_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
