# Generated by Django 2.0.3 on 2018-04-05 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('please_website_app', '0022_leadsperimeter_logsendsms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='documents/category/')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='please_website_app.City')),
            ],
        ),
        migrations.RenameModel(
            old_name='LeadsPerimeter',
            new_name='LogLeadForm',
        ),
    ]
