# Generated by Django 2.0.3 on 2018-04-06 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('please_website_app', '0024_candidatecitymanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=500, null=True)),
                ('last_name', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=500, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('licence', models.NullBooleanField()),
                ('auto', models.NullBooleanField()),
                ('sent_to_bereglo', models.NullBooleanField()),
                ('bereglo_token', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=500, null=True)),
                ('last_name', models.CharField(blank=True, max_length=500, null=True)),
                ('business_name', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=500, null=True)),
                ('percentage', models.IntegerField(blank=True, null=True)),
                ('business_type', models.CharField(choices=[('Restaurant', 'Restaurant'), ('Fast Food', 'Fast Food'), ('Bien-Etre & Beauté', 'Bien-Etre & Beauté'), ('Boulangerie & Petit-Déjeuner', 'Boulangerie & Petit-Déjeuner'), ('Epicerie de Quartier', 'Epicerie de Quartier'), ('Service', 'Service')], default='Restaurant', max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='candidatecitymanager',
            name='restaurants',
        ),
        migrations.RemoveField(
            model_name='candidatecitymanager',
            name='shops',
        ),
        migrations.AddField(
            model_name='candidatecitymanager',
            name='business_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatecitymanager',
            name='density',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatecitymanager',
            name='empty_housing_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatecitymanager',
            name='housing_price_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatecitymanager',
            name='main_housing_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatecitymanager',
            name='net_salary_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatecitymanager',
            name='service_business_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatecitymanager',
            name='unemployment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='city_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='please_website_app.CandidateCityManager'),
        ),
        migrations.AddField(
            model_name='deliveryman',
            name='city_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='please_website_app.CandidateCityManager'),
        ),
    ]
