# Generated by Django 2.0.3 on 2018-04-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_website_app', '0026_auto_20180406_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='siret',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
