# Generated by Django 2.0.3 on 2018-04-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_website_app', '0028_candidatecitymanager_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryman',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='documents/delivery_man/'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='documents/merchant/'),
        ),
    ]
