# Generated by Django 2.0.3 on 2018-04-09 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('please_website_app', '0030_remove_article_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryman',
            name='birth_date',
        ),
    ]
