# Generated by Django 2.0.3 on 2018-04-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_website_app', '0031_remove_deliveryman_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='conciergerie_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
