# Generated by Django 2.0.3 on 2018-04-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_website_app', '0033_auto_20180411_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='delivery',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='business_type',
            field=models.CharField(choices=[('Restaurant', 'Restaurant'), ('Fast Food', 'Fast Food'), ('Bien-Etre & Beauté', 'Bien-Etre & Beauté'), ('Boulangerie & Petit-Déjeuner', 'Boulangerie & Petit-Déjeuner'), ('Epicerie de Quartier', 'Epicerie de Quartier'), ('Epicerie Fine', 'Epicerie Fine'), ('Course et Marché', 'Course et Marché'), ('Gourmandises', 'Gourmandises'), ('Service', 'Service')], default='Restaurant', max_length=500),
        ),
    ]
