# Generated by Django 2.0.3 on 2018-04-11 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('please_website_app', '0034_auto_20180411_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryman',
            name='bereglo_token',
        ),
        migrations.RemoveField(
            model_name='deliveryman',
            name='licence',
        ),
    ]
