# Generated by Django 2.0.3 on 2018-04-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_website_app', '0035_auto_20180411_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='gps_coordinates',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
