# Generated by Django 2.0.3 on 2018-04-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_website_app', '0036_city_gps_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='gps_coordinates_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='gps_coordinates_long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
