# Generated by Django 2.0.3 on 2018-04-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_website_app', '0038_auto_20180417_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='cm_image',
            field=models.ImageField(blank=True, null=True, upload_to='documents/city/'),
        ),
    ]
