# Generated by Django 2.0.3 on 2018-04-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_website_app', '0040_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
