# Generated by Django 2.0.3 on 2018-04-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_website_app', '0041_auto_20180417_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='abstract',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
