# Generated by Django 2.0.3 on 2019-05-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_website_app', '0045_auto_20190514_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatecitymanager',
            name='competition',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
