# Generated by Django 3.1.5 on 2021-01-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_website_app', '0047_auto_20190802_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='top',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='candidatecitymanager',
            name='task_completed',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='deliveryman',
            name='auto',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='deliveryman',
            name='sent_to_bereglo',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='competition',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='delivery',
            field=models.BooleanField(null=True),
        ),
    ]
